### PR TITLE
Update the blog to use Bedrock & Forge.

### LINKED ISSUE #79: Embedded videos too wide on mobile & desktop
https://blog.dosomething.org/

img_0099

img_0098

### PR DESCRIPTION
**Pull request by DFurnes**
Updates the blog to use [Bedrock](https://roots.io/bedrock) for a modern Wordpress environment, and [Forge](http://forge.dosomething.org) for consistent and maintainable styles. This closes #79, #80, #81, and #82.

Before deploying, we'll need to make a `.env` file on production, and configure the server to host files out of the `web` subdirectory (instead of the repository root).

For review: @angaither @weerd

### CODE REVIEW

**Comment by angaither** [comment]
this is the most.

**Comment by weerd** [comment]
@DFurnes maybe just walk us through the cliff notes on this PR, haha. GH can't even load all the files! :scream:

**Comment by DFurnes** [comment]
Yeah, totally. It's probably easiest to just take a look at the [branch itself](https://github.com/DoSomething/dosomething-blog/tree/bedrock-forge), rather than the diff. Basically, we had a whole Wordpress installation checked into source control, and now we don't. The other major changes are in the [`web/app/themes/dosomething`](https://github.com/DoSomething/dosomething-blog/tree/bedrock-forge/web/app/themes/dosomething) directory, which is a new theme built on [Underscores](http://underscores.me) and [Forge](http://forge.dosomething.org).

**Comment by angaither** [comment]
i love it :+1:

**Pull request merged**
